"""
Data + pairing engine for BarBeerQue.

Rather than hand-writing a fixed list of pairings, each beer and food is
scored on real flavor/texture attributes (1-5 scale). The matching engine
below applies actual beer-pairing principles -- contrast (bitterness/
carbonation cutting through fat), complement (malt/roast echoing char and
smoke), and balance (avoiding clashes like high bitterness against high
spice heat) -- so every one of the 900 possible food/beer combinations is
genuinely reasoned, not just the ones written by hand.

Attribute scale for all values below: 1 (low) to 5 (high).
"""

# --- BEERS ------------------------------------------------------------
# bitterness: hop bitterness / IBU character
# malt_sweetness: caramel/malt-forward sweetness
# roastiness: roasted/coffee/dark-malt character
# carbonation: fizz/crispness, palate-cleansing quality
# body: how heavy/full the beer feels

BEERS = [
    {"name": "Budweiser", "style": "American Lager",
     "bitterness": 2, "malt_sweetness": 2, "roastiness": 1, "carbonation": 4, "body": 2,
     "notes": ["crisp", "light-bodied", "clean"]},
    {"name": "Bud Light", "style": "American Light Lager",
     "bitterness": 1, "malt_sweetness": 1, "roastiness": 1, "carbonation": 4, "body": 1,
     "notes": ["ultra-light", "crisp", "easy-drinking"]},
    {"name": "Miller Lite", "style": "American Light Lager",
     "bitterness": 1, "malt_sweetness": 1, "roastiness": 1, "carbonation": 4, "body": 1,
     "notes": ["light", "crisp", "refreshing"]},
    {"name": "Coors Light", "style": "American Light Lager",
     "bitterness": 1, "malt_sweetness": 1, "roastiness": 1, "carbonation": 5, "body": 1,
     "notes": ["very crisp", "cold-forward", "light"]},
    {"name": "Coors Banquet", "style": "American Lager",
     "bitterness": 2, "malt_sweetness": 2, "roastiness": 1, "carbonation": 4, "body": 2,
     "notes": ["smooth", "lightly malty", "clean"]},
    {"name": "Michelob Ultra", "style": "Light Lager",
     "bitterness": 1, "malt_sweetness": 1, "roastiness": 1, "carbonation": 4, "body": 1,
     "notes": ["ultra-light", "dry", "neutral"]},
    {"name": "Yuengling Traditional Lager", "style": "American Amber Lager",
     "bitterness": 2, "malt_sweetness": 3, "roastiness": 2, "carbonation": 3, "body": 3,
     "notes": ["lightly caramel", "smooth", "balanced"]},
    {"name": "Modelo Especial", "style": "Mexican Lager",
     "bitterness": 2, "malt_sweetness": 2, "roastiness": 1, "carbonation": 4, "body": 2,
     "notes": ["crisp", "lightly sweet", "citrus-friendly"]},
    {"name": "Corona Extra", "style": "Mexican Lager",
     "bitterness": 1, "malt_sweetness": 1, "roastiness": 1, "carbonation": 4, "body": 1,
     "notes": ["light", "crisp", "citrusy"]},
    {"name": "Pacifico", "style": "Mexican Pilsner",
     "bitterness": 2, "malt_sweetness": 2, "roastiness": 1, "carbonation": 4, "body": 2,
     "notes": ["crisp", "lightly hoppy", "refreshing"]},
    {"name": "Dos Equis Lager Especial", "style": "Mexican Lager",
     "bitterness": 2, "malt_sweetness": 2, "roastiness": 1, "carbonation": 4, "body": 2,
     "notes": ["smooth", "lightly toasty", "crisp"]},
    {"name": "Tecate", "style": "Mexican Lager",
     "bitterness": 2, "malt_sweetness": 1, "roastiness": 1, "carbonation": 4, "body": 1,
     "notes": ["crisp", "dry", "minerally"]},
    {"name": "Heineken", "style": "European Pale Lager",
     "bitterness": 3, "malt_sweetness": 2, "roastiness": 1, "carbonation": 4, "body": 2,
     "notes": ["crisp", "lightly bitter", "herbal"]},
    {"name": "Stella Artois", "style": "Belgian Pilsner",
     "bitterness": 3, "malt_sweetness": 2, "roastiness": 1, "carbonation": 4, "body": 2,
     "notes": ["crisp", "floral", "clean finish"]},
    {"name": "Blue Moon Belgian White", "style": "Witbier",
     "bitterness": 1, "malt_sweetness": 3, "roastiness": 1, "carbonation": 3, "body": 2,
     "notes": ["citrus", "coriander-spiced", "smooth"]},
    {"name": "Sam Adams Boston Lager", "style": "Vienna Lager",
     "bitterness": 3, "malt_sweetness": 3, "roastiness": 2, "carbonation": 3, "body": 3,
     "notes": ["toasty malt", "balanced hops", "smooth"]},
    {"name": "Sam Adams Summer Ale", "style": "Wheat Ale",
     "bitterness": 2, "malt_sweetness": 2, "roastiness": 1, "carbonation": 3, "body": 2,
     "notes": ["citrus", "lemony", "light"]},
    {"name": "Sierra Nevada Pale Ale", "style": "American Pale Ale",
     "bitterness": 4, "malt_sweetness": 3, "roastiness": 1, "carbonation": 3, "body": 3,
     "notes": ["piney hops", "citrus", "balanced malt"]},
    {"name": "Sierra Nevada Torpedo", "style": "American IPA",
     "bitterness": 5, "malt_sweetness": 3, "roastiness": 1, "carbonation": 3, "body": 3,
     "notes": ["big hop bitterness", "grapefruit", "resinous"]},
    {"name": "Lagunitas IPA", "style": "American IPA",
     "bitterness": 5, "malt_sweetness": 2, "roastiness": 1, "carbonation": 3, "body": 3,
     "notes": ["hoppy", "citrus-pine", "dry finish"]},
    {"name": "Founders All Day IPA", "style": "Session IPA",
     "bitterness": 4, "malt_sweetness": 2, "roastiness": 1, "carbonation": 3, "body": 2,
     "notes": ["hoppy but light", "citrus", "easy-drinking"]},
    {"name": "Bell's Two Hearted Ale", "style": "American IPA",
     "bitterness": 5, "malt_sweetness": 3, "roastiness": 1, "carbonation": 3, "body": 3,
     "notes": ["bold grapefruit hops", "balanced malt", "smooth bitterness"]},
    {"name": "Dogfish Head 60 Minute IPA", "style": "American IPA",
     "bitterness": 5, "malt_sweetness": 2, "roastiness": 1, "carbonation": 3, "body": 3,
     "notes": ["continuously hopped", "citrus-pine", "dry"]},
    {"name": "Fat Tire", "style": "Amber Ale",
     "bitterness": 2, "malt_sweetness": 4, "roastiness": 2, "carbonation": 3, "body": 3,
     "notes": ["toasty caramel", "biscuity", "smooth"]},
    {"name": "Newcastle Brown Ale", "style": "English Brown Ale",
     "bitterness": 2, "malt_sweetness": 4, "roastiness": 3, "carbonation": 2, "body": 3,
     "notes": ["nutty", "caramel", "smooth malt"]},
    {"name": "Shiner Bock", "style": "American Bock",
     "bitterness": 2, "malt_sweetness": 4, "roastiness": 2, "carbonation": 3, "body": 3,
     "notes": ["rich malt", "lightly sweet", "smooth"]},
    {"name": "Negra Modelo", "style": "Munich Dunkel / Dark Lager",
     "bitterness": 2, "malt_sweetness": 4, "roastiness": 3, "carbonation": 3, "body": 3,
     "notes": ["caramel", "light roast", "smooth"]},
    {"name": "Guinness Draught", "style": "Irish Dry Stout",
     "bitterness": 3, "malt_sweetness": 2, "roastiness": 5, "carbonation": 2, "body": 3,
     "notes": ["roasted coffee", "creamy", "dry finish"]},
    {"name": "Founders Porter", "style": "Robust Porter",
     "bitterness": 3, "malt_sweetness": 4, "roastiness": 5, "carbonation": 2, "body": 4,
     "notes": ["dark chocolate", "roasted", "rich"]},
    {"name": "Left Hand Milk Stout", "style": "Milk Stout",
     "bitterness": 2, "malt_sweetness": 5, "roastiness": 4, "carbonation": 2, "body": 4,
     "notes": ["chocolate", "creamy sweet", "smooth"]},
]

# --- BBQ FOODS ----------------------------------------------------------
# richness: fat content / heaviness on the palate
# smokiness: smoke exposure / smoked intensity
# spice_heat: chili/spice heat level
# sweetness: sweetness of glaze, sauce, or the food itself
# char: caramelization / charred, seared surface intensity

FOODS = [
    {"name": "Pulled Pork", "category": "BBQ",
     "richness": 4, "smokiness": 5, "spice_heat": 1, "sweetness": 3, "char": 2,
     "notes": ["smoky", "fatty", "sauce-forward"]},
    {"name": "Brisket", "category": "BBQ",
     "richness": 5, "smokiness": 5, "spice_heat": 1, "sweetness": 1, "char": 3,
     "notes": ["rich", "smoky bark", "beefy"]},
    {"name": "Beef Ribs", "category": "BBQ",
     "richness": 5, "smokiness": 4, "spice_heat": 1, "sweetness": 1, "char": 3,
     "notes": ["fatty", "smoky", "deeply beefy"]},
    {"name": "Baby Back Ribs", "category": "BBQ",
     "richness": 4, "smokiness": 3, "spice_heat": 1, "sweetness": 4, "char": 3,
     "notes": ["glazed", "tender", "smoky-sweet"]},
    {"name": "St. Louis Ribs", "category": "BBQ",
     "richness": 4, "smokiness": 4, "spice_heat": 1, "sweetness": 3, "char": 3,
     "notes": ["fatty", "smoky", "saucy"]},
    {"name": "BBQ Chicken", "category": "BBQ",
     "richness": 2, "smokiness": 3, "spice_heat": 1, "sweetness": 3, "char": 3,
     "notes": ["glazed", "charred skin", "lighter meat"]},
    {"name": "Smoked Chicken Wings", "category": "BBQ",
     "richness": 3, "smokiness": 4, "spice_heat": 2, "sweetness": 2, "char": 2,
     "notes": ["smoky", "crisp skin", "savory"]},
    {"name": "Buffalo Wings", "category": "BBQ",
     "richness": 3, "smokiness": 1, "spice_heat": 4, "sweetness": 1, "char": 1,
     "notes": ["spicy", "tangy", "buttery"]},
    {"name": "Grilled Chicken Breast", "category": "BBQ",
     "richness": 1, "smokiness": 1, "spice_heat": 1, "sweetness": 1, "char": 2,
     "notes": ["lean", "light", "mild"]},
    {"name": "Burnt Ends", "category": "BBQ",
     "richness": 5, "smokiness": 5, "spice_heat": 1, "sweetness": 3, "char": 5,
     "notes": ["intensely smoky", "caramelized", "rich"]},
    {"name": "Cheeseburger", "category": "Grill",
     "richness": 4, "smokiness": 1, "spice_heat": 1, "sweetness": 1, "char": 3,
     "notes": ["fatty", "charred", "savory"]},
    {"name": "Hot Dog", "category": "Grill",
     "richness": 3, "smokiness": 2, "spice_heat": 1, "sweetness": 1, "char": 2,
     "notes": ["salty", "snappy", "grilled"]},
    {"name": "Bratwurst", "category": "Grill",
     "richness": 4, "smokiness": 1, "spice_heat": 1, "sweetness": 1, "char": 2,
     "notes": ["juicy", "peppery", "rich"]},
    {"name": "Italian Sausage", "category": "Grill",
     "richness": 4, "smokiness": 1, "spice_heat": 2, "sweetness": 1, "char": 2,
     "notes": ["fennel-spiced", "juicy", "savory"]},
    {"name": "Grilled Shrimp", "category": "Seafood",
     "richness": 1, "smokiness": 1, "spice_heat": 1, "sweetness": 1, "char": 2,
     "notes": ["light", "sweet-briny", "delicate"]},
    {"name": "Grilled Salmon", "category": "Seafood",
     "richness": 3, "smokiness": 2, "spice_heat": 1, "sweetness": 1, "char": 2,
     "notes": ["rich", "oily", "flaky"]},
    {"name": "BBQ Meatballs", "category": "BBQ",
     "richness": 3, "smokiness": 1, "spice_heat": 1, "sweetness": 3, "char": 1,
     "notes": ["saucy", "savory", "tender"]},
    {"name": "Grilled Corn on the Cob", "category": "Side",
     "richness": 2, "smokiness": 1, "spice_heat": 1, "sweetness": 3, "char": 2,
     "notes": ["sweet", "buttery", "charred"]},
    {"name": "Baked Beans", "category": "Side",
     "richness": 2, "smokiness": 2, "spice_heat": 1, "sweetness": 4, "char": 1,
     "notes": ["sweet", "smoky", "hearty"]},
    {"name": "Coleslaw", "category": "Side",
     "richness": 1, "smokiness": 1, "spice_heat": 1, "sweetness": 2, "char": 1,
     "notes": ["cool", "tangy", "crisp"]},
    {"name": "Mac and Cheese", "category": "Side",
     "richness": 5, "smokiness": 1, "spice_heat": 1, "sweetness": 1, "char": 1,
     "notes": ["creamy", "rich", "cheesy"]},
    {"name": "Cornbread", "category": "Side",
     "richness": 3, "smokiness": 1, "spice_heat": 1, "sweetness": 3, "char": 1,
     "notes": ["sweet", "buttery", "crumbly"]},
    {"name": "Grilled Vegetables", "category": "Side",
     "richness": 1, "smokiness": 1, "spice_heat": 1, "sweetness": 2, "char": 3,
     "notes": ["light", "charred", "earthy"]},
    {"name": "Smoked Turkey Leg", "category": "BBQ",
     "richness": 3, "smokiness": 4, "spice_heat": 1, "sweetness": 1, "char": 2,
     "notes": ["smoky", "savory", "lean-ish"]},
    {"name": "Pork Belly Burnt Ends", "category": "BBQ",
     "richness": 5, "smokiness": 5, "spice_heat": 1, "sweetness": 4, "char": 5,
     "notes": ["intensely rich", "candied", "smoky"]},
    {"name": "Filet Mignon", "category": "Steak",
     "richness": 3, "smokiness": 1, "spice_heat": 1, "sweetness": 1, "char": 3,
     "notes": ["tender", "buttery", "mild"]},
    {"name": "Ribeye Steak", "category": "Steak",
     "richness": 5, "smokiness": 1, "spice_heat": 1, "sweetness": 1, "char": 4,
     "notes": ["fatty", "beefy", "charred crust"]},
    {"name": "Tri-Tip", "category": "Steak",
     "richness": 3, "smokiness": 2, "spice_heat": 1, "sweetness": 1, "char": 3,
     "notes": ["beefy", "peppery crust", "lean-ish"]},
    {"name": "Carne Asada", "category": "Grill",
     "richness": 3, "smokiness": 1, "spice_heat": 2, "sweetness": 1, "char": 4,
     "notes": ["citrus-marinated", "charred", "savory"]},
    {"name": "Al Pastor Tacos", "category": "Grill",
     "richness": 3, "smokiness": 1, "spice_heat": 3, "sweetness": 2, "char": 3,
     "notes": ["spiced", "charred pineapple-sweet", "savory"]},
]
